apiVersion: v1
kind: ConfigMap
metadata:
  name: skyflo-version
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
data:
  VERSION: {{ include "skyflo.version" . | quote }}
