{{- if .Values.ui }}
{{- if .Values.ui.enabled }}
{{- $global := index .Values "global" | default dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skyflo.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ include "skyflo.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ include "skyflo.fullname" . }}-ui
        {{- with $global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $global.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      {{- else }}
      {{- with $global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default (include "skyflo.version" .) }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: skyflo-ui-config
        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: skyflo-version
              key: VERSION
        resources:
          {{- toYaml .Values.ui.resources.ui | nindent 10 }}
        {{- with $global.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: proxy
        image: "{{ .Values.ui.proxyImage.repository }}:{{ .Values.ui.proxyImage.tag | default (include "skyflo.version" .) }}"
        imagePullPolicy: {{ .Values.ui.proxyImage.pullPolicy }}
        ports:
        - containerPort: 80
          name: http-proxy
        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: skyflo-version
              key: VERSION
        resources:
          {{- toYaml .Values.ui.resources.proxy | nindent 10 }}
      terminationGracePeriodSeconds: 10
      {{- with $global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
