apiVersion: v1
kind: Secret
metadata:
  name: skyflo-engine-secrets
  namespace: skyflo-ai
type: Opaque
stringData:
  GROQ_API_KEY: ""
  LLM_MODEL: "groq/llama-3.3-70b-versatile"
  JWT_SECRET: "c2t5ZmxvLXRlc3QtanN0LXNlY3JldC0zMmJ5dGVzLWNoYW5nZS1pbi1wcm9k"
  POSTGRES_DATABASE_URL: "postgres://skyflo:skyflo@skyflo-ai-postgres:5432/skyflo"
  REDIS_URL: "redis://skyflo-ai-redis:6379/0"
