apiVersion: v1
kind: Secret
metadata:
  name: skyflo-postgres-secrets
  namespace: skyflo-ai
type: Opaque
stringData:
  POSTGRES_USER: "skyflo"
  POSTGRES_PASSWORD: "skyflo"
  POSTGRES_DB: "skyflo"
  POSTGRES_PORT: "5432"
