{{- if .Values.engine }}
{{- if .Values.engine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyflo.fullname" . }}-engine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.engine.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "skyflo.fullname" . }}-engine
{{- end }}
{{- end }}
