{{- if .Values.mcp }}
{{- if .Values.mcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyflo.fullname" . }}-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mcp.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "skyflo.fullname" . }}-mcp
{{- end }}
{{- end }}
