{{- if .Values.ui }}
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyflo.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "skyflo.fullname" . }}-ui
  ports:
  - name: http
    port: {{ .Values.ui.service.port }}
    targetPort: http-proxy
    protocol: TCP
  - name: ui-http
    port: {{ .Values.ui.service.uiPort }}
    targetPort: http
    protocol: TCP
{{- end }}
{{- end }}
