apiVersion: v1
kind: Service
metadata:
  name: skyflo-ai-ui
  namespace: skyflo-ai
spec:
  type: ClusterIP
  selector:
    app: skyflo-ai-ui
  ports:
  - name: http
    port: 80
    targetPort: http-proxy
    protocol: TCP
  - name: ui-http
    port: 3000
    targetPort: http
    protocol: TCP
