apiVersion: v1
kind: Service
metadata:
  name: skyflo-ai-ui
  namespace: skyflo-ai
spec:
  ports:
  - port: 80
    targetPort: http-proxy
    protocol: TCP
    name: http
  - port: 3000
    targetPort: http
    protocol: TCP
    name: ui-http
  type: ClusterIP
  selector:
    app: skyflo-ai-ui
