{{- if .Values.postgres }}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: skyflo-postgres-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyflo.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.postgresSecret }}
  POSTGRES_USER: {{ .user | quote }}
  POSTGRES_PASSWORD: {{ .password | quote }}
  POSTGRES_DB: {{ .database | quote }}
  POSTGRES_PORT: {{ .port | quote }}
{{- end }}
{{- end }}
{{- end }}
